### ISSUE TITLE
自定义词典包含空格时报错

### ISSUE THREAD

**Issue by ningpp** [huaban/jieba-analysis#25]
Exception in thread "main" java.lang.NumberFormatException: For input string: "server"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1241)
	at java.lang.Double.valueOf(Double.java:504)
	at com.huaban.analysis.jieba.WordDictionary.loadUserDict(WordDictionary.java:151)
	at com.huaban.analysis.jieba.WordDictionary.loadUserDict(WordDictionary.java:134)

报错的词是sql server

**Comment by piaolingxue** [comment]
@ningpp 目前 jieba 主要致力于中文分词，对英文只支持简单的空格分词，你说的这个情况跟字典格式有关，目前格式是
```
词 词频 [词性]
```
以空格标准，不过我可以改成分隔符自定义，默认空格
