### ISSUE TITLE
在Solr5.5.2中使用结巴分词1.0.2时报错!

### ISSUE THREAD

**Issue by giantchou** [huaban/jieba-analysis#37]
@piaolingxue  你好：我下载你的jieba-analysis和analyzer-solr(https://github.com/sing1ee/analyzer-solr.git)在Solr5.5.2中使用，配置文件如下：
< fieldType name="text_jieba" class="solr.TextField" positionIncrementGap="100">
< analyzer type="index">
< tokenizer class="analyzer.solr5.jieba.JiebaTokenizerFactory" segMode="SEARCH"/>
< filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt" />
< filter class="solr.LowerCaseFilterFactory"/>
< filter class="solr.SnowballPorterFilterFactory" language="English"/>
< /analyzer>
< analyzer type="query">
< tokenizer class="analyzer.solr5.jieba.JiebaTokenizerFactory" segMode="SEARCH"/>
< filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt" />
< filter class="solr.SynonymFilterFactory" synonyms="synonyms.txt" ignoreCase="true" expand="true"/>
< filter class="solr.LowerCaseFilterFactory"/>
< filter class="solr.SnowballPorterFilterFactory" language="English"/>
< /analyzer>
< /fieldType>

报错信息如下：
2016/8/11 下午3:10:33 ERROR null HttpSolrCall null:java.lang.RuntimeException: java.lang.NoSuchFieldError: word
null:java.lang.RuntimeException: java.lang.NoSuchFieldError: word
at org.apache.solr.servlet.HttpSolrCall.sendError(HttpSolrCall.java:607)
at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:475)
at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:257)
at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:208)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
.................
Caused by: java.lang.NoSuchFieldError: word
at analyzer.solr5.jieba.JiebaTokenizer.incrementToken(JiebaTokenizer.java:38)
at org.apache.solr.handler.AnalysisRequestHandlerBase.analyzeTokenStream(AnalysisRequestHandlerBase.java:188)
at org.apache.solr.handler.AnalysisRequestHandlerBase.analyzeValue(AnalysisRequestHandlerBase.java:127)
at org.apache.solr.handler.FieldAnalysisRequestHandler.analyzeValues(FieldAnalysisRequestHandler.java:220)
at org.apache.solr.handler.FieldAnalysisRequestHandler.handleAnalysisRequest(FieldAnalysisRequestHandler.java:181)
.............

请问我是哪里配置错了？该如何解决，谢谢！！！

**Comment by piaolingxue** [comment]
@giantchou 你好，可能是版本问题，analyzer-solr 好久没更新了，你切到低版本分词试下？另外我推荐你用 elasticsearch，目前花瓣在用，好用，谁用谁知道。我们有维护 elasticsearch 对应的插件: https://github.com/huaban/elasticsearch-analysis-jieba

**Comment by giantchou** [comment]
@piaolingxue  收到，谢谢
